### ISSUE TITLE
May I bundle `mruby-errno` to `mruby` itself?

### ISSUE THREAD

**Issue by matz** [iij/mruby-errno#3]
As we did for `mruby-io` and `mruby-socket`.

**Comment by tsahara** [comment]
Yes, you can.  We are glad that we can contribute another mrbgem to mruby core.

But I do not know it works well with the latest version of mruby because we use it on mruby-1.3.

**Comment by matz** [comment]
Thank you. We will copy it and fix it if necessary.

**Comment by matz** [comment]
Merged by mruby/mruby@0a6d57ab3c3f2c09bb5471834b615a21693f7033
